### ISSUE TITLE
Change event not called when a checkfield/radiofield's label is clicked

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/uxf#10]
## Description

Clicking a radio field's label changes the radio field's selection state, however, it doesn't trigger the "change" event like clicking on the box does. The same happens for checkfields.

**Comment by joamag** [comment]
please don't use the term **checkfield label** as it's confusing because it's not part of uxf... you're referring **checkfield** and **radiofield** right ? How are you changing their value ?

**Comment by tsilva** [comment]
@joamag **checkfield** and **radiofield** have support for clickable labels (in uxf), in checkfield it selects "check-field-label".

**Comment by joamag** [comment]
@tsilva that's not uxf that's the default label support from html, labels can change the state on a `input[type=check]` out of the box

**Comment by tsilva** [comment]
@joamag https://github.com/hivesolutions/uxf/blob/bad3db44885e21b46099ec506a5d1bd07b61a0b2/js/ui/check_field.part.js#L54

**Comment by joamag** [comment]
This is now closed
