### ISSUE TITLE
Dropdown components have no support for uxvalue

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/uxf#11]
## Descriptions

Most components respond to `uxvalue()`, like "dropfield" for example, however "dropdown" does not. To guarantee that components have an uniform way of accessing their values, this should be implemented for `dropdown` as well.

**Comment by joamag** [comment]
This is already implemented, closing as won't fix. Check https://github.com/hivesolutions/uxf/blob/master/js/ui/drop_down.part.js#L424 for concrete implementation details.

**Comment by joamag** [comment]
Reopening as the set behaviour is the wanted one...
