### ISSUE TITLE
Support for ISO country codes data source

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/uxf#12]
## Description

The iso countries data source uses the country name as both the identifier and the display value:

https://github.com/hivesolutions/uxf/blob/ceaea455126c5b7c35f9daec17d723d905eb4692/js/data/data_source_isocountries.part.js

https://github.com/hivesolutions/uxf/blob/ceaea455126c5b7c35f9daec17d723d905eb4692/js/locale/base.en_iso.part.js

It would be useful to have a data source where the identifier values are two letter iso country codes.

**Comment by joamag** [comment]
@tsilva you must use the `data-iso="iso2"` attribute in the data-source
