### ISSUE TITLE
Performing uxreset on a dropdown does not erase label

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/uxf#13]
## Description

When performing "uxreset" on a "dropdown" component, the input is erased, the selected list item is unselected, but the label in the button still shows the selection.

**Comment by joamag** [comment]
@tsilva can't repro any issue, what I get is the correct behaviour (before and after uxreset):

![before](https://cloud.githubusercontent.com/assets/25441/11093022/8bb683c8-887f-11e5-8ea6-17bba72b3f9f.png)

![after](https://cloud.githubusercontent.com/assets/25441/11093026/8e3b0ca4-887f-11e5-9c87-ebc1961c528f.png)

This has been performed on http://layout_demo.stage.hive.pt/random using:

``` javascript
jQuery(jQuery(".drop-down")[2]).uxreset()
```

**Comment by tsilva** [comment]
@joamag `data-name` is mandatory

**Comment by joamag** [comment]
@tsilva removed requirement for `data-name` closing this issue.
