### ISSUE TITLE
Checkfields toggle when check-field-label is clicked even when disabled

### ISSUE THREAD

**Issue by tsilva** [hivesolutions/uxf#6]
## Description

With the following code, when the user clicks the "check-field" nothing happens because it's disabled (expected behaviour). However, when the user clicks the label the "check-field" still toggles.

``` html
<div class="check-input disabled">
      <input type="checkbox" class="check-field disabled" disabled="1" value="1" data-checked="1" />
      <label class="check-field-label">Label</label>
</div>
```
## Solution

Make the "check-field-label" click event abort when the "check-field" is disabled.

**Comment by tsilva** [comment]
@joamag Same thing is happening in "radio-field".

**Comment by joamag** [comment]
@tsilva ok we'll take a look at it

**Comment by joamag** [comment]
this should now be fixed
