### ISSUE TITLE
Support for html tags in drop-down button

### ISSUE THREAD

**Issue by rui-castro** [hivesolutions/uxf#7]
## Description

Currently, to set the content of `.button-drop-down` there's a data attribute `data-name` in the &lt;ul> element, like this:

``` html
<ul class="drop-down drop-down-size" data-name="{{ 'Your size'|locale }} ({{ country|locale }})" data-input="size">
...
```

This produces the following html

``` html
<div class="drop-down-container visible">
  <div class="button button-drop-down drop-down-size">Your size (France)</div>
...
</div>
```

With this approach is not possible to include html notation in the `.button-drop-down` contents, to produce something like this

``` html
<div class="drop-down-container visible">
  <div class="button button-drop-down drop-down-size">Your size <span class="scale">France</span></div>
  ...
</div>
```

**Comment by rui-castro** [comment]
@joamag This is now fixed, right?

**Comment by joamag** [comment]
This is now fixed using `uxcontent()`
